# Generated by Django 3.0.3 on 2021-05-08 19:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import formula_one.utils.upload_to
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_PERSON_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('link', models.URLField(blank=True)),
                ('images', models.FileField(blank=True, upload_to=formula_one.utils.upload_to.UploadTo('r_care', 'r_care_files'))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=63)),
                ('pin_code', models.IntegerField(validators=[django.core.validators.RegexValidator('^[0-9]{3,9}$'), django.core.validators.MinValueValidator(0)])),
                ('address', models.TextField()),
                ('verification', models.CharField(choices=[('verified_by_me', 'Verified By Me'), ('verified_by_someone_else', 'Verified By Someone Else'), ('not_verified', 'Not Verified')], default='verified_by_me', max_length=50)),
                ('other_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('downvotes', models.ManyToManyField(blank=True, related_name='leads_downvotes', to=settings.KERNEL_PERSON_MODEL)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.KERNEL_PERSON_MODEL)),
                ('upvotes', models.ManyToManyField(blank=True, related_name='leads_upvotes', to=settings.KERNEL_PERSON_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('pin_code', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('^[0-9]{3,9}$'), django.core.validators.MinValueValidator(0)])),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=63)),
                ('patient_spo2', models.PositiveIntegerField(blank=True, null=True)),
                ('patient_ct_value', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('fulfilled', 'Fulfilled'), ('not_required_anymore', 'Not Required Anymore')], default='active', max_length=50)),
                ('other_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.KERNEL_PERSON_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('resource_type', models.CharField(choices=[('oxygen', 'Oxygen'), ('plasma', 'Plasma'), ('remdesivir_tocilizumab', 'Remdesivir & Tocilizumab'), ('fabiflu_favipiravir', 'Fabiflu & Favipiravir'), ('hospital_beds', 'Hospital beds'), ('icu_and_ventilator', 'ICU & Ventilator'), ('other', 'Other')], max_length=63)),
                ('requirement', models.TextField(blank=True, null=True)),
                ('patient_blood_group', models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='r_care.Request')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlasmaDonor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('blood_group', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('tested_positive', models.BooleanField(default=False)),
                ('positive_when', models.DateField(blank=True, null=True)),
                ('vaccinated', models.BooleanField(default=False)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plasma_donor', to='r_care.Lead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('resource_type', models.CharField(choices=[('oxygen', 'Oxygen'), ('plasma', 'Plasma'), ('remdesivir_tocilizumab', 'Remdesivir & Tocilizumab'), ('fabiflu_favipiravir', 'Fabiflu & Favipiravir'), ('hospital_beds', 'Hospital beds'), ('icu_and_ventilator', 'ICU & Ventilator'), ('other', 'Other')], max_length=63)),
                ('cost', models.PositiveIntegerField(blank=True, null=True)),
                ('capacity', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='r_care.Lead')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
