# Generated by Django 3.0.3 on 2021-05-01 19:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import formula_one.utils.upload_to
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.KERNEL_PERSON_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('link', models.URLField()),
                ('images', models.FileField(blank=True, upload_to=formula_one.utils.upload_to.UploadTo('Covid_Care', 'covid_care_files'))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlasmaDonor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=127)),
                ('contact', models.CharField(max_length=31)),
                ('blood_group', models.CharField(max_length=3)),
                ('tested_positive', models.BooleanField(default=False)),
                ('positive_when', models.DateField(blank=True, null=True)),
                ('vaccinated', models.BooleanField(default=False)),
                ('pin_code', models.IntegerField(validators=[django.core.validators.RegexValidator('^[0-9]{3,9}$'), django.core.validators.MinValueValidator(0)])),
                ('address', models.CharField(max_length=255)),
                ('other_contact', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('resource_type', models.CharField(choices=[('oxygen', 'Oxygen'), ('plasma', 'Plasma'), ('remdesivir_tocilizumab', 'Remdesivir & Tocilizumab'), ('fabiflu_favipiravir', 'Fabiflu & Favipiravir'), ('hospital_beds', 'Hospital beds'), ('icu_and_ventilator', 'ICU & Ventilator'), ('other', 'Other')], max_length=50)),
                ('cost', models.PositiveIntegerField()),
                ('capacity', models.CharField(max_length=15)),
                ('requirement', models.TextField(max_length=127)),
                ('patient_blood_group', models.CharField(max_length=2)),
                ('description', models.TextField(max_length=255)),
                ('entity_object_id', models.PositiveIntegerField()),
                ('entity_content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'Covid_Care'), ('model', 'request')), models.Q(('app_label', 'Covid_Care'), ('model', 'lead')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('pin_code', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('^[0-9]{3,9}$'), django.core.validators.MinValueValidator(0)])),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=63)),
                ('patient_spo2', models.PositiveIntegerField()),
                ('patient_ct_value', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('fulfilled', 'Fulfilled'), ('not_required_anymore', 'Not Required Anymore')], max_length=50)),
                ('other_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_uploader', to=settings.KERNEL_PERSON_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=63)),
                ('pin_code', models.IntegerField(validators=[django.core.validators.RegexValidator('^[0-9]{3,9}$'), django.core.validators.MinValueValidator(0)])),
                ('address', models.CharField(max_length=255)),
                ('verification', models.CharField(choices=[('verified_by_me', 'Verified By Me'), ('verified_by_someone_else', 'Verified By Someone Else'), ('not_verified', 'Not Verified')], max_length=50)),
                ('other_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('downvotes', models.ManyToManyField(related_name='leads_downvotes', to=settings.KERNEL_PERSON_MODEL)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_uploader', to=settings.KERNEL_PERSON_MODEL)),
                ('upvotes', models.ManyToManyField(related_name='leads_upvotes', to=settings.KERNEL_PERSON_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
