# Generated by Django 3.0.3 on 2021-05-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Covid_Care', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinnew',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='plasmadonor',
            name='blood_group',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='plasmadonor',
            name='name',
            field=models.CharField(max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='capacity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='patient_blood_group',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='requirement',
            field=models.TextField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('oxygen', 'Oxygen'), ('plasma', 'Plasma'), ('remdesivir_tocilizumab', 'Remdesivir & Tocilizumab'), ('fabiflu_favipiravir', 'Fabiflu & Favipiravir'), ('hospital_beds', 'Hospital beds'), ('icu_and_ventilator', 'ICU & Ventilator'), ('other', 'Other')], max_length=63),
        ),
    ]
