# Generated by Django 3.0.3 on 2021-05-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_care', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='verification',
            field=models.CharField(choices=[('verified_by_me', 'Verified By Me'), ('verified_by_someone_else', 'Verified By Someone Else'), ('not_verified', 'Not Verified')], default='verified_by_me', max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='patient_ct_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='patient_spo2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('fulfilled', 'Fulfilled'), ('not_required_anymore', 'Not Required Anymore')], default='active', max_length=50),
        ),
    ]
