# Generated by Django 3.0.3 on 2021-05-02 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_PERSON_MODEL),
        ('Covid_Care', '0002_auto_20210502_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='leads_downvotes', to=settings.KERNEL_PERSON_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='leads_upvotes', to=settings.KERNEL_PERSON_MODEL),
        ),
        migrations.AlterField(
            model_name='plasmadonor',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resource',
            name='requirement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
