# Generated by Django 3.0.3 on 2021-05-05 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_PERSON_MODEL),
        ('covid_care', '0002_auto_20210506_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.KERNEL_PERSON_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.KERNEL_PERSON_MODEL),
        ),
    ]
