# Generated by Django 3.0.3 on 2021-05-02 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Covid_Care', '0003_auto_20210502_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plasma_request', to='Covid_Care.Request'),
        ),
    ]
