# Generated by Django 3.0.3 on 2021-05-02 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Covid_Care', '0004_resource_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='request',
        ),
        migrations.AddField(
            model_name='plasmadonor',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plasma_request', to='Covid_Care.Request'),
        ),
    ]
