# Generated by Django 3.0.3 on 2021-05-02 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Covid_Care', '0005_auto_20210502_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plasmadonor',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plasma_request', to='Covid_Care.Request'),
        ),
    ]
